version: 0.2
phases:
  pre_build:
    commands:
      - dotnet restore slnTestAWS/AWSServerless1/AWSServerless1.csproj   
  build:
    commands:
      - dotnet publish -c release -o ./build_output  slnTestAWS/AWSServerless1/AWSServerless1.csproj
  post_build:
    commands:
      - aws s3 sync build_output/ s3://mbo-backend-s3
artifacts:
  files:
    - build_output/**/*
    - scripts/**/*
